import { buildWorld, challenge, identify, order, scenario } from "../factory";

export const comfyUiSkill = buildWorld({
  id: "comfyui",
  name: "ComfyUI",
  fantasy: "THE AI WORKFLOW ARTIST",
  tagline: "Nodes in. A machine out.",
  description: "Graphs, samplers, ControlNet, LoRA, inpaint, video, and a reusable cinematic machine — simulated canvas only, no live Comfy runtime.",
  category: "AI Worlds",
  difficulty: "intermediate",
  hours: 14,
  icon: "workflow",
  trial: {
    key: "trial",
    title: "Fix this broken graph",
    summary: "A wire is wrong. You read the sockets. You do not queue a prompt.",
    minutes: 4,
    concept: { key: "trial", name: "Graph instincts", axis: "problem" },
    teach: {
      title: "Types on the wires",
      body: "MODEL, CLIP, VAE, LATENT, IMAGE. A red wire is a type lie. The sampler wants a model, not tokens.",
      bullets: ["Colour is a type", "Unconnected required sockets are empty pictures", "This world never runs the graph"],
    },
    example: {
      title: "CLIP into KSampler MODEL",
      body: "KSampler MODEL input is fed CLIP text. The graph is a type lie. Checkpoint MODEL should land on the sampler. CLIP should land on encode.",
      callout: "You score the wiring, not a PNG.",
    },
    questions: [
      scenario(
        "KSampler has no MODEL input. CLIP text is wired into it instead. Fix?",
        "Simulated graph. Red socket on MODEL.",
        ["Ignore the colour", "Checkpoint loader MODEL → KSampler, CLIP → encode", "Delete VAE", "Raise CFG to 30"],
        1,
        "The sampler wants a model, not tokens.",
      ),
      identify(
        "Which socket is the compressed picture?",
        "MODEL / CLIP / LATENT / IMAGE",
        ["LATENT", "MODEL", "CLIP", "A seed"],
        0,
        "Latents are compressed.",
      ),
      order("Default txt2img.", ["Load checkpoint", "CLIP encode prompt", "KSampler", "VAE decode", "Save image"], "Sample in latent, then decode."),
      identify(
        "Empty output, no toast. First look?",
        "A required input on KSampler is disconnected.",
        ["Unconnected required sockets", "Buy a new PC first", "Raise CFG", "Tweet the JSON"],
        0,
        "Follow the red.",
      ),
    ],
  },
  levels: [
    {
      key: "enter",
      title: "Enter the Node World",
      subtitle: "Load → prompt → generate",
      missions: [
        {
          key: "sockets",
          title: "A node is a function",
          summary: "Inputs, outputs, a picture — on paper.",
          concept: { key: "sockets", name: "Nodes and wires", axis: "knowledge" },
          teach: {
            title: "Don't mix types",
            body: "Load checkpoint. Encode prompt. Sample latents. Decode. Save. MODEL is weights. CLIP is text encoder. IMAGE is pixels.",
            bullets: ["Wires are typed", "Save sits after decode", "You will not hit Queue Prompt here"],
          },
          example: {
            title: "Default chain",
            body: "Checkpoint → MODEL into KSampler, CLIP into two encoders. Encoders → conditioning. KSampler → LATENT → VAE Decode → IMAGE → Save.",
            callout: "If Save sits on LATENT, you saved noise soup.",
          },
          questions: [
            order("Default txt2img.", ["Load checkpoint", "CLIP encode prompt", "KSampler", "VAE decode", "Save image"], "Sample in latent, then decode."),
            identify(
              "MODEL socket is for…",
              "A) Weights for the sampler  B) Text encoder  C) Compressed image  D) Pixels",
              ["Weights for the sampler", "Text encoder", "Compressed image", "Pixels"],
              0,
              "Don't mix types.",
            ),
            identify(
              "CLIP socket is for…",
              "A) Weights  B) Text encoder  C) Compressed image  D) Pixels",
              ["Text encoder", "Weights", "Latent", "Pixels"],
              0,
              "CLIP encodes words.",
            ),
            scenario(
              "Save Image is wired to LATENT, not IMAGE.",
              "Simulated.",
              ["Decode first, then save pixels", "Raise CFG", "Delete VAE", "Ignore colour"],
              0,
              "Pixels after decode.",
            ),
          ],
        },
        {
          key: "ckpt",
          title: "One checkpoint, three gifts",
          summary: "MODEL, CLIP, VAE from the loader.",
          concept: { key: "ckpt", name: "Checkpoint loader", axis: "knowledge" },
          teach: {
            title: "Don't orphan CLIP",
            body: "If CLIP floats unconnected, prompts do nothing. If VAE is missing, you cannot decode. The loader is a bundle, not a sticker.",
          },
          example: {
            title: "Orphan",
            body: "MODEL wired. CLIP dangling. Positive prompt node sits alone. The sampler cooks unconditioned noise.",
            callout: "Every gift needs a home.",
          },
          questions: [
            identify(
              "Missing home?",
              "Loader: MODEL → KSampler. CLIP unused. Two CLIPTextEncode nodes empty of CLIP.",
              ["CLIP not into encoders", "Need more seeds", "Need CFG 30", "Need a LoRA at 3.0"],
              0,
              "Wire CLIP.",
            ),
            order("Use a loader.", ["Drop checkpoint loader", "MODEL → sampler", "CLIP → both encoders", "VAE → decode"], "Bundle to homes."),
            scenario(
              "Decode node has no VAE. Output is blank.",
              "Simulated.",
              ["Loader VAE → VAE Decode", "Raise steps to 1000", "Delete the prompt", "New PC"],
              0,
              "VAE decodes.",
            ),
          ],
        },
        {
          key: "empty-latent",
          title: "The blank you sample into",
          summary: "Width, height, batch — a bucket of noise.",
          concept: { key: "empty-latent", name: "Empty latent", axis: "execution" },
          teach: {
            title: "Size is a choice",
            body: "64×64 is a stamp. 1024×1024 is a poster and a VRAM bill. Batch 8 is eight stamps. This is a diagram of knobs, not a run.",
          },
          questions: [
            identify(
              "CFG 22, 4 steps, 64×64. Result you should expect?",
              "Simulated knobs only.",
              ["Undercooked, fried, tiny", "A museum print", "Video", "A LoRA"],
              0,
              "Steps cook. CFG seasons. Resolution is size.",
            ),
            scenario(
              "You wanted a poster. Empty latent is 64×64, batch 1.",
              "No upscale later.",
              ["Raise latent size (or plan an upscale stage)", "CFG 30 will enlarge it", "Delete VAE", "More negatives"],
              0,
              "Size is the bucket.",
            ),
            order("Start a canvas.", ["Pick width/height", "Empty latent", "Sampler", "Decode"], "Bucket, then cook."),
          ],
        },
        {
          key: "first-graph",
          title: "Mini-project: The first graph",
          summary: "On paper: loader, encode, sample, decode, save.",
          kind: "project",
          minutes: 12,
          concept: { key: "first-graph", name: "First graph", axis: "execution" },
          teach: {
            title: "No queue",
            body: "If a stranger can follow the wires without a red socket, you shipped v0.1.",
          },
          questions: [
            challenge(
              "The first graph",
              "Simulated txt2img. No runtime.",
              [
                { question: "First node?", options: ["Save Image", "Load checkpoint", "A random LoRA at 4.0", "Video combine"], answer: 1, explanation: "Weights first." },
                { question: "Prompt path?", options: ["CLIP text into MODEL", "CLIP → encode → sampler conditioning", "Skip CLIP", "VAE into prompt"], answer: 1, explanation: "Encode." },
                { question: "Last?", options: ["Save the latent soup", "VAE decode then Save Image", "Delete decode", "Tweet JSON"], answer: 1, explanation: "Pixels." },
              ],
              "Load, encode, sample, decode, save.",
              "hard",
              100,
            ),
          ],
        },
      ],
    },
    {
      key: "ctrl",
      title: "Control",
      subtitle: "Resolution, seed, sampler, steps, CFG",
      missions: [
        {
          key: "seed",
          title: "Seeds are the save file",
          summary: "Same seed + same graph ≈ same image.",
          concept: { key: "seed", name: "Seeds", axis: "execution" },
          teach: {
            title: "Write them down",
            body: "The number that picks a noise pattern is the seed. You cannot reproduce a look without noting seed or checkpoint. Simulated knobs only.",
          },
          example: {
            title: "Lost look",
            body: "A hero frame. Seed forgotten. Checkpoint swapped. The “same prompt” is a different film.",
            callout: "Log seed, ckpt, sampler, steps, CFG, size.",
          },
          questions: [
            identify(
              "The number that picks a noise pattern is the…",
              "seed / CFG / VAE / LoRA",
              ["seed", "CFG", "VAE", "a watermark"],
              0,
              "Seed.",
            ),
            scenario(
              "You can reproduce a look without noting seed or checkpoint.",
              "True or false as a design claim.",
              ["False — write them down", "True — prompts are enough", "True — CFG stores identity", "True — VAE is the save"],
              0,
              "Log the knobs.",
            ),
            order("Lock a look.", ["Note checkpoint", "Note seed", "Note sampler/steps/CFG", "Note size"], "A recipe, not a wish."),
          ],
        },
        {
          key: "cfg-steps",
          title: "Cook and season",
          summary: "Steps cook. CFG seasons. Too much fries contrast.",
          concept: { key: "cfg-steps", name: "CFG and steps", axis: "execution" },
          teach: {
            title: "Lock the knobs",
            body: "CFG too high fries contrast. 4 steps is raw dough. You will not slide sliders in a live UI here.",
          },
          example: {
            title: "Fried",
            body: "CFG 22, 4 steps, 64×64. Undercooked, fried, tiny. Not a museum print.",
            callout: "More CFG is not more quality past a point.",
          },
          questions: [
            identify(
              "CFG 22, 4 steps, 64×64. Result?",
              "Simulated.",
              ["Undercooked, fried, tiny", "A museum print", "Video", "A LoRA"],
              0,
              "Cook and size.",
            ),
            scenario(
              "Contrast looks like a comic with glowing edges.",
              "CFG 18, 12 steps, otherwise sane.",
              ["Lower CFG", "Raise CFG to 40", "Delete CLIP", "Seed 0 is illegal"],
              0,
              "Season down.",
            ),
            identify(
              "Raw dough look, structure missing.",
              "2 steps, CFG 4, huge latent.",
              ["Not enough steps", "Need CFG 40", "Need 6 checkpoints loaded", "Need a watermark"],
              0,
              "Cook longer.",
            ),
          ],
        },
        {
          key: "sampler-pick",
          title: "The cook has a name",
          summary: "Euler, DPM, ancestral — pick and log it.",
          concept: { key: "sampler-pick", name: "Samplers", axis: "knowledge" },
          teach: {
            title: "Don't swap mid-series",
            body: "Ancestral samplers add noise each step. A locked stills series wants a deterministic cook. Switching sampler is a new recipe.",
          },
          questions: [
            identify(
              "You need matching stills for a character sheet.",
              "Swap sampler every image “for variety.”",
              ["Lock sampler + seed family", "Randomise everything", "CFG 30", "New checkpoint each frame"],
              0,
              "Hold the cook.",
            ),
            order("Reproduce a still.", ["Same ckpt", "Same sampler", "Same seed", "Same size/steps/CFG"], "The whole recipe."),
            scenario(
              "Flicker city on a video graph. First lock?",
              "Simulated.",
              ["Seed + ControlNet/reference", "Randomise everything", "CFG 30", "New checkpoint each frame"],
              0,
              "Hold identity.",
            ),
          ],
        },
        {
          key: "boss-knobs",
          title: "Boss: The Fried Stamp",
          summary: "Art dir wanted a poster. You got a burnt postage stamp.",
          kind: "boss",
          minutes: 14,
          concept: { key: "boss-knobs", name: "Knob emergency", axis: "problem" },
          teach: {
            title: "Four faults",
            body: "Tiny latent, four steps, CFG 22, forgotten seed. Fix the recipe. Do not add six checkpoints.",
          },
          questions: [
            challenge(
              "THE FRIED STAMP",
              "64×64, 4 steps, CFG 22, seed unknown, CLIP unwired. Simulated.",
              [
                { question: "Size?", options: ["Keep 64", "Raise latent (or plan upscale)", "CFG will enlarge", "Delete VAE"], answer: 1, explanation: "Bucket." },
                { question: "Cook?", options: ["Stay at 4 steps", "Enough steps to form structure", "0 steps is faster", "Steps are decorative"], answer: 1, explanation: "Cook." },
                { question: "Season?", options: ["Keep CFG 22", "Bring CFG back to a sane band", "CFG 40", "CFG 0 always"], answer: 1, explanation: "Don't fry." },
                { question: "Identity?", options: ["Forget seed", "Wire CLIP and log seed+ckpt", "New ckpt every click", "Tweet JSON"], answer: 1, explanation: "Recipe." },
              ],
              "Size, cook, season, log.",
              "hard",
              250,
            ),
          ],
        },
      ],
    },
    {
      key: "cond",
      title: "Conditioning",
      subtitle: "Positive, negative, CLIP",
      missions: [
        {
          key: "pos-neg",
          title: "Push and pull",
          summary: "Two prompts, one sample.",
          concept: { key: "pos-neg", name: "Conditioning", axis: "execution" },
          teach: {
            title: "Negative is a ban list",
            body: "Positive describes. Negative subtracts artefacts: extra fingers, watermark, blur. A 400-word positive is noise.",
          },
          questions: [
            identify(
              "Watermarks keep appearing. First?",
              "Simulated.",
              ["Negative: watermark, text, logo — and check dataset bias", "Buy a new GPU", "CFG 1", "Delete CLIP"],
              0,
              "Negatives + awareness.",
            ),
            scenario(
              "A 400-word positive prompt is always better.",
              "Design claim.",
              ["False — noise, be specific", "True — always", "True if you omit negative", "True if seed is 0"],
              0,
              "Specific beats novels.",
            ),
            order("Condition.", ["Write a concrete positive", "Short negative ban list", "Encode both", "Into sampler"], "Push, pull, encode."),
          ],
        },
        {
          key: "two-encoders",
          title: "Two CLIP boxes",
          summary: "Positive and negative are two encodes, not one novel.",
          concept: { key: "two-encoders", name: "Dual encode", axis: "knowledge" },
          teach: {
            title: "Don't share one box",
            body: "If both conditionings come from one encode, you cannot ban watermarks without also describing them into existence.",
          },
          questions: [
            identify(
              "Missing piece?",
              "One CLIPTextEncode wired to both sampler conditionings.",
              ["Separate positive and negative encodes", "Need more adjectives", "Need a bigger seed", "Need negative empty always"],
              0,
              "Two boxes.",
            ),
            scenario(
              "Negative list includes “watermark” but it is concatenated into the positive encode.",
              "Simulated.",
              ["Split encodes — don't mix the ban into the ask", "Raise CFG", "Delete VAE", "Load 6 checkpoints"],
              0,
              "Split.",
            ),
            identify(
              "Positive should describe…",
              "A) What should exist  B) Only bans  C) The seed  D) VRAM",
              ["What should exist", "Only bans", "The seed", "VRAM"],
              0,
              "Describe.",
            ),
          ],
        },
        {
          key: "clip-skip",
          title: "Which layer of language",
          summary: "CLIP skip is a flavour, not a fix for bad wires.",
          concept: { key: "clip-skip", name: "CLIP skip", axis: "problem" },
          teach: {
            title: "Don't skip to hide a dangling CLIP",
            body: "If CLIP isn't wired, skip does nothing useful. Flavour comes after a legal graph.",
          },
          questions: [
            scenario(
              "Prompts do nothing. CLIP skip set to 12. CLIP still dangling.",
              "Simulated.",
              ["Wire CLIP first", "Skip 99", "CFG 40", "Delete encode"],
              0,
              "Wires before flavour.",
            ),
            identify(
              "When to touch skip?",
              "Graph is legal, look is too literal / too mushy.",
              ["After the graph is legal", "Instead of wiring", "Instead of a checkpoint", "Instead of VAE"],
              0,
              "Last.",
            ),
            order("Debug mute prompts.", ["Check CLIP wired", "Check encode → sampler", "Then consider skip", "Then consider ckpt"], "Legal, then taste."),
          ],
        },
      ],
    },
    {
      key: "cnet",
      title: "ControlNet",
      subtitle: "Pose, depth, edges, structure",
      missions: [
        {
          key: "pose",
          title: "Follow this pose",
          summary: "Structure is a condition. Simulated apply, not a live preprocessor.",
          concept: { key: "pose", name: "ControlNet", axis: "execution" },
          teach: {
            title: "A preprocessor, then a model",
            body: "OpenPose from a photo → ControlNet → sampler. Strength is a mixer. Strength 0 is control off.",
          },
          questions: [
            identify(
              "Missing piece?",
              "KSampler ← prompt only. No ControlNet. You wanted a specific pose.",
              ["Need pose preprocessor + ControlNet apply", "Need more adjectives", "Need a bigger seed", "Need negative empty"],
              0,
              "Structure needs a control.",
            ),
            identify(
              "OpenPose is for…",
              "A) Body layout  B) Near/far  C) Outlines  D) Control off",
              ["Body layout", "Near/far", "Outlines", "Control off"],
              0,
              "Pose.",
            ),
            identify(
              "Depth is for…",
              "A) Body layout  B) Near/far  C) Outlines  D) Control off",
              ["Near/far", "Body layout", "Outlines", "Off"],
              0,
              "Depth.",
            ),
            scenario(
              "Strength 0. Pose ignored. User angry.",
              "ControlNet node present.",
              ["Strength 0 is control off — raise it", "Need more adjectives", "Delete pose image", "CFG 30"],
              0,
              "Mixer.",
            ),
          ],
        },
        {
          key: "maps",
          title: "Pick the map for the job",
          summary: "Edges vs pose vs depth.",
          concept: { key: "maps", name: "Control maps", axis: "knowledge" },
          teach: {
            title: "The photo is not the map",
            body: "You preprocess. Canny wants outlines. OpenPose wants a skeleton. Feeding a colour JPEG into the wrong model is a muddy suggestion.",
          },
          questions: [
            identify(
              "Canny / edges is for…",
              "A) Body layout  B) Near/far  C) Outlines  D) Control off",
              ["Outlines", "Body", "Depth", "Off"],
              0,
              "Edges.",
            ),
            order("Pose lock.", ["Source photo", "OpenPose preprocessor", "ControlNet apply", "Sampler"], "Map, then mix."),
            scenario(
              "You wanted a city layout. You used OpenPose on a skyline photo.",
              "Simulated.",
              ["Depth or canny from the layout, not a skeleton", "Raise pose strength to 3", "More LoRAs", "Delete VAE"],
              0,
              "Right map.",
            ),
          ],
        },
        {
          key: "strength",
          title: "The mixer",
          summary: "Too much control: a tracing. Too little: a shrug.",
          concept: { key: "strength", name: "Control strength", axis: "execution" },
          teach: {
            title: "Start mid",
            body: "If the character must hit a board pose, raise strength. If you only want a hint of architecture, lower it. Don't max every slider.",
          },
          questions: [
            identify(
              "Traced look, no style left.",
              "ControlNet strength 1.4 plus two LoRAs at 1.2.",
              ["Lower control and LoRA weights", "Raise all to 3", "Delete the checkpoint", "Only use negative"],
              0,
              "Over-weight fights.",
            ),
            scenario(
              "Pose almost ignored.",
              "Strength 0.15, preprocessor skipped (raw photo into pose model).",
              ["Real OpenPose map + mid strength", "Strength 0", "CFG 40", "Six checkpoints"],
              0,
              "Map then mix.",
            ),
            order("Tune control.", ["Legal wires", "Correct preprocessor", "Mid strength", "Nudge after a still"], "Then taste."),
          ],
        },
      ],
    },
    {
      key: "lora",
      title: "LoRA",
      subtitle: "Styles and characters",
      missions: [
        {
          key: "weight",
          title: "A consistent style",
          summary: "Small files, big look. Stack carefully.",
          concept: { key: "weight", name: "LoRA", axis: "execution" },
          teach: {
            title: "Clip strength separately sometimes",
            body: "Load LoRA on MODEL+CLIP. Weight 0.6–1.0. Character melts when two LoRAs sit at 1.2 each.",
          },
          questions: [
            identify(
              "Character melts when two LoRAs sit at 1.2 each. Fix?",
              "Simulated.",
              ["Lower weights, or bake one look", "Raise both to 3", "Delete the checkpoint", "Only use negative"],
              0,
              "Over-weight fights.",
            ),
            identify(
              "A small extra weight file for a style or person is a…",
              "lora / seed / VAE / CFG",
              ["lora", "seed", "VAE", "CFG"],
              0,
              "LoRA.",
            ),
            scenario(
              "Identity: hope. No LoRA, no ref, new face each node.",
              "Cinematic city brief.",
              ["Character LoRA/ref + ControlNet pose + locked seed family", "New face each node", "Only negatives", "CFG 30"],
              0,
              "Lock identity.",
            ),
          ],
        },
        {
          key: "stack",
          title: "Order of clothes",
          summary: "Checkpoint, then LoRA, then control.",
          concept: { key: "stack", name: "Stack order", axis: "knowledge" },
          teach: {
            title: "Don't LoRA a missing MODEL",
            body: "LoRA applies to a model stream. If it sits on an empty wire, it is jewellery on a ghost.",
          },
          questions: [
            order("Dress the model.", ["Load checkpoint", "Apply LoRA to MODEL/CLIP", "ControlNet", "Sampler"], "Base, style, structure."),
            identify(
              "LoRA node MODEL in is empty.",
              "Checkpoint MODEL goes around it straight to sampler.",
              ["LoRA is bypassed — wire through it", "Need more weight", "Need CFG", "Need video"],
              0,
              "Through, not around.",
            ),
            scenario(
              "Style LoRA at 2.0, character LoRA at 2.0, ControlNet 1.5.",
              "Melted soup.",
              ["Drop weights; pick a hero LoRA", "Raise all", "Delete CLIP", "More steps only"],
              0,
              "One hero look.",
            ),
          ],
        },
        {
          key: "trigger",
          title: "The word that wakes it",
          summary: "A trigger token is a doorbell, not a novel.",
          concept: { key: "trigger", name: "Triggers", axis: "execution" },
          teach: {
            title: "Use the trained word",
            body: "If the LoRA card says ohwx person, your positive needs that doorbell. “same lady” is not the doorbell.",
          },
          questions: [
            identify(
              "LoRA trained on ohwx. Prompt says “same lady” only.",
              "Simulated.",
              ["Add the trigger token", "Raise weight to 5", "Delete negative", "New seed each word"],
              0,
              "Doorbell.",
            ),
            scenario(
              "Two character LoRAs, two triggers, both at 1.0.",
              "Faces blend.",
              ["One character per pass, or lower one to near zero", "Both at 3", "Skip CLIP", "CFG 40"],
              0,
              "One hero.",
            ),
            order("Use a character LoRA.", ["Read the card", "Put trigger in positive", "Modest weight", "Lock seed family"], "Doorbell, then mix."),
          ],
        },
      ],
    },
    {
      key: "xform",
      title: "Image Transformation",
      subtitle: "img2img, inpaint, outpaint",
      missions: [
        {
          key: "inpaint",
          title: "Repair and extend",
          summary: "Mask is the instruction. Simulated denoise, not a live brush.",
          concept: { key: "inpaint", name: "Inpaint", axis: "execution" },
          teach: {
            title: "Denoise is how much you let go",
            body: "Low denoise: keep structure. High: reinvent. Inpaint only the mask. Outpainting is inpaint with the canvas grown.",
          },
          questions: [
            scenario(
              "You wanted to fix a hand. The whole face changed.",
              "Likely?",
              ["Mask too big / denoise too high", "Need more steps only", "VAE missing is unrelated", "Seed 0 is illegal"],
              0,
              "Mask tight. Denoise modest.",
            ),
            identify(
              "Outpainting is…",
              "inpaint with the canvas grown / a new checkpoint / CFG / a seed",
              ["inpaint with the canvas grown", "a new checkpoint", "CFG", "illegal"],
              0,
              "Same family.",
            ),
            order("Fix a hand.", ["Tight mask", "Modest denoise", "Same seed family", "Check the rest of the face"], "Local edit."),
          ],
        },
        {
          key: "i2i",
          title: "Honour the still",
          summary: "img2img is a nudge, not a teleport.",
          concept: { key: "i2i", name: "img2img", axis: "execution" },
          teach: {
            title: "Denoise again",
            body: "Low keeps the set. High invents a new city. If wardrobe must hold, don't crank denoise and rewrite the prompt into a desert.",
          },
          questions: [
            identify(
              "Product photo → “slow orbit later.” Best denoise for a still refine?",
              "Simulated.",
              ["Low — keep the object", "1.0 — new planet", "Skip VAE", "CFG 40"],
              0,
              "Honour the still.",
            ),
            scenario(
              "Green coat night market becomes desert noon.",
              "img2img denoise 0.9 plus a new place prompt.",
              ["Lower denoise and lock place in the prompt", "Higher denoise", "Delete ControlNet always", "Six LoRAs"],
              0,
              "Don't teleport.",
            ),
            identify(
              "Mask covers the whole image for a “hand fix.”",
              "Simulated.",
              ["That's img2img in disguise — shrink the mask", "Perfect inpaint", "Need more CFG", "Need video"],
              0,
              "Mask is the instruction.",
            ),
          ],
        },
        {
          key: "adv",
          title: "Mini-project: Multi-stage graph",
          summary: "Draft → control → detail → upscale. Diagram only.",
          kind: "project",
          minutes: 12,
          concept: { key: "adv", name: "Multi-stage", axis: "execution" },
          teach: {
            title: "Pass images as inputs",
            body: "Don't do every job in one KSampler. Cheap first, expensive last. You will not run it.",
          },
          questions: [
            challenge(
              "A quality pipeline",
              "Simulated stages.",
              [
                { question: "First?", options: ["4K face restore", "Low-res draft", "Six checkpoints", "Video"], answer: 1, explanation: "Cheap first." },
                { question: "Then?", options: ["Tweet JSON", "Structure/control pass", "Delete latent", "CFG 40 only"], answer: 1, explanation: "Structure." },
                { question: "Late?", options: ["Detail pass then upscale then repair if needed", "Repair first always", "Skip decode", "Random seeds each stage"], answer: 0, explanation: "Expensive last." },
              ],
              "Cheap first, expensive last.",
              "hard",
              100,
            ),
          ],
        },
      ],
    },
    {
      key: "video",
      title: "Video",
      subtitle: "Frames that agree",
      missions: [
        {
          key: "flicker",
          title: "Motion graphs",
          summary: "Consistency is the boss of video. No live animate.",
          concept: { key: "flicker", name: "Video consistency", axis: "execution" },
          teach: {
            title: "Lock what must not flicker",
            body: "Seed, ControlNet, a reference frame. Animate one axis at a time. Shuffle seeds is a strobe.",
          },
          questions: [
            identify(
              "Flicker city. First lock?",
              "Simulated.",
              ["Seed + ControlNet/reference", "Randomise everything", "CFG 30", "New checkpoint each frame"],
              0,
              "Hold identity.",
            ),
            scenario(
              "Camera move wanted. You shuffle seeds across 24 stills.",
              "Simulated.",
              ["Image-to-video / interp from a locked still with one axis of motion", "12 unrelated stills", "Raise CFG", "New face each node"],
              0,
              "One motion from a locked still.",
            ),
            order("A short move.", ["Lock still + seed family", "One axis of camera motion", "Hold identity (ControlNet/ref)", "Check flicker"], "One axis."),
          ],
        },
        {
          key: "vram",
          title: "Make the graph a product",
          summary: "Reusable, inspectable. Don't OOM on purpose.",
          concept: { key: "vram", name: "Graph hygiene", axis: "problem" },
          teach: {
            title: "Name nodes. Group. Prune.",
            body: "VRAM: smaller latents, fewer unused models loaded. Bypass vs delete. Load 6 checkpoints “just in case” and you will OOM. Simulated advice — no GPU here.",
          },
          questions: [
            identify(
              "Load 6 checkpoints at once “just in case.”",
              "Simulated VRAM.",
              ["You will OOM — load what you use", "Fine always", "Required for CLIP", "Required for seeds"],
              0,
              "Don't.",
            ),
            identify(
              "Debug start?",
              "Empty output, no error toast",
              ["Check unconnected required sockets", "Buy a new PC first", "Raise CFG", "Tweet the JSON"],
              0,
              "Follow the red.",
            ),
            scenario(
              "Unused branch still loads a second SDXL.",
              "Bypass exists.",
              ["Bypass or unload the unused ckpt", "Keep both hot", "Raise CFG", "Add LoRAs at 3"],
              0,
              "Prune.",
            ),
          ],
        },
        {
          key: "groups",
          title: "A machine, not a one-off",
          summary: "Name, group, version the JSON.",
          concept: { key: "groups", name: "Reusable graphs", axis: "knowledge" },
          teach: {
            title: "The brief is a factory",
            body: "Futuristic city. Recurring character. Consistent style. Camera movement. One graph family — stills and a short move of the same hero.",
          },
          questions: [
            identify(
              "City structure best from…",
              "A) Prompt soup  B) Depth/canny from a layout + style LoRA  C) Random noise  D) A screenshot of Maps as MODEL",
              ["Depth/canny from a layout + style LoRA", "Prompt soup", "Random noise", "Maps as MODEL"],
              0,
              "Structure the set.",
            ),
            order("Factory stills.", ["Lock ckpt+LoRA+seed family", "ControlNet layout", "Generate still", "I2V one axis"], "Same machine."),
            scenario(
              "Each still is a new graph with new names and new weights.",
              "Client wanted a series.",
              ["Clone one versioned graph", "Keep inventing", "Six checkpoints per still", "Skip ControlNet always"],
              0,
              "A machine.",
            ),
          ],
        },
      ],
    },
    {
      key: "final",
      title: "Final Boss: Build the Machine",
      subtitle: "A cinematic city, a recurring character, camera move",
      isBoss: true,
      missions: [
        {
          key: "final",
          title: "BUILD THE MACHINE",
          summary: "The brief is a factory. Simulated graph family. No queue.",
          kind: "boss",
          minutes: 18,
          concept: { key: "final", name: "Cinematic factory", axis: "problem" },
          teach: {
            title: "The brief",
            body: "Futuristic city. Recurring character. Consistent style. Camera movement. One graph family. You are scored on wiring and locks, not on a rendered MP4.",
          },
          questions: [
            challenge(
              "BUILD THE MACHINE",
              "Need stills and a short camera move of the same hero in the same city. Simulated only.",
              [
                { question: "Identity?", options: ["Hope", "Character LoRA/ref + ControlNet pose + locked seed family", "New face each node", "Only negatives"], answer: 1, explanation: "Lock identity." },
                { question: "City?", options: ["Prompt soup", "Depth/canny from a layout + style LoRA", "Random noise", "A screenshot of Maps as MODEL"], answer: 1, explanation: "Structure the set." },
                { question: "Wires?", options: ["CLIP into MODEL", "Legal types: MODEL/CLIP/VAE/LATENT/IMAGE in the right homes", "Save the latent soup", "Six unused checkpoints"], answer: 1, explanation: "Types." },
                { question: "Camera move?", options: ["Shuffle seeds", "Image-to-video / frame interp from a still with one axis of motion", "12 unrelated stills", "Raise CFG"], answer: 1, explanation: "One motion from a locked still." },
              ],
              "A machine, not a one-off.",
              "hard",
              1000,
            ),
          ],
        },
      ],
    },
  ],
});
