import { buildWorld, challenge, identify, order, scenario } from "../factory";

export const n8nSkill = buildWorld({
  id: "n8n",
  name: "n8n",
  fantasy: "THE AUTOMATION ENGINEER",
  tagline: "Trigger → action → output. Then the whole company.",
  description: "Workflows, apps, JSON, logic, APIs, loops, AI steps, and a business system — designed on paper, never executed here.",
  category: "AI Worlds",
  difficulty: "beginner",
  hours: 12,
  icon: "zap",
  trial: {
    key: "trial",
    title: "Automate this workflow",
    summary: "Form in. Email out. Don't overbuild. This world is a sim — you choose nodes, you do not run n8n.",
    minutes: 4,
    concept: { key: "trial", name: "Workflow instincts", axis: "execution" },
    teach: {
      title: "The smallest path",
      body: "Webhook or form trigger. Map fields. Send email. Stop. A 40-node AI mesh is how inbound dies in staging.",
      bullets: ["Happy path first", "One sample payload", "Credentials live in a vault, not the canvas"],
    },
    example: {
      title: "Lead ping",
      body: "Trigger: form submitted. Map name + email. Gmail node. Test with one row. No CRM, no agents, no loop.",
      callout: "You are scoring the graph, not executing it.",
    },
    questions: [
      order("First automation.", ["Trigger: form submitted", "Map name and email", "Send email node", "Test with one sample"], "Happy path first."),
      identify(
        "What is this node?",
        "On form submitted → …",
        ["Trigger", "A random Function", "An error path", "A cron"],
        0,
        "The start is a trigger.",
      ),
      scenario(
        "Sales wants “AI agents for everything” on day one. What do you ship?",
        "Inbound is a Typeform. The job is “don't miss the lead.”",
        ["Form → map → email, then stop", "Twelve agents and a vector DB", "No workflow — a spreadsheet forever", "A 200-node monster"],
        0,
        "Smallest path.",
      ),
      identify(
        "Dangerous design?",
        "workflow.json includes \"apiKey\": \"sk-live-…\" in a Set node.",
        ["Secret on the canvas", "Fine for GitHub", "Safer than a credential store", "Required by HTTP"],
        0,
        "Vault, not JSON.",
      ),
    ],
  },
  levels: [
    {
      key: "think",
      title: "Think in Workflows",
      subtitle: "Trigger → action → output",
      missions: [
        {
          key: "boxes",
          title: "Three boxes",
          summary: "Something happens. You work. Something leaves.",
          concept: { key: "boxes", name: "Workflow shape", axis: "knowledge" },
          teach: {
            title: "Name the parts",
            body: "A trigger starts the run. Actions transform or call apps. Output is the side effect you can audit: a mail, a row, a ticket.",
            bullets: ["No trigger, no run", "Test input is not production traffic", "One job per workflow until it hurts"],
          },
          example: {
            title: "Form → mail",
            body: "Trigger: form. Action: map. Output: sent message. Sample payload sits in the test pin, not in a live webhook yet.",
            callout: "If you cannot name the output, you do not have a workflow.",
          },
          questions: [
            identify(
              "Which line is the trigger?",
              "A) Form submitted  B) Send Gmail  C) The sent message  D) A sample payload",
              ["A — Form submitted", "B — Send Gmail", "C — The sent message", "D — A sample payload"],
              0,
              "Triggers start.",
            ),
            order("Happy path.", ["Trigger fires", "Map fields", "Action node", "Confirm output"], "Start, map, do, check."),
            scenario(
              "A “workflow” is a sticky note: “someone emails sales.”",
              "No trigger, no node, no output.",
              ["That is a hope, not a system", "It will run at midnight", "n8n infers the rest", "It is already production"],
              0,
              "Boxes or it isn't built.",
            ),
            identify(
              "What is a sample payload?",
              "{ \"email\": \"ada@studio.test\", \"name\": \"Ada\" } pinned on the trigger.",
              ["Test input", "A credential", "A cron", "An error handler"],
              0,
              "You rehearse with a pin.",
            ),
          ],
        },
        {
          key: "when",
          title: "When does it start?",
          summary: "Webhook, form, cron, app event — pick one.",
          concept: { key: "when", name: "Trigger types", axis: "knowledge" },
          teach: {
            title: "Time vs event",
            body: "Cron is a clock. Webhook is a knock. App trigger is “a row was added.” Mixing all three on one canvas is how duplicates are born.",
          },
          example: {
            title: "Wrong clock",
            body: "Lead form already posts a webhook. You also cron-poll the sheet every minute. Sales gets two pings.",
            callout: "One birth event.",
          },
          questions: [
            identify(
              "Best trigger for “a human just submitted a form”?",
              "Options in the palette: Cron, Webhook/Form, Manual, Interval 50ms.",
              ["Webhook / form", "Cron every minute on the same sheet", "Interval 50ms", "Manual only forever"],
              0,
              "The knock is the form.",
            ),
            order("Choose a start.", ["Name the real-world event", "Pick webhook vs cron vs app", "Forbid a second birth event", "Pin a sample"], "One birth."),
            scenario(
              "Weekly KPI ping to Slack. No human event.",
              "Numbers live in a warehouse.",
              ["Cron → query → Slack", "Webhook from a ghost form", "Manual every Friday and hope", "100 parallel HTTP nodes"],
              0,
              "Clocks for reports.",
            ),
          ],
        },
        {
          key: "stop",
          title: "Know when to stop",
          summary: "A workflow that never ends is a bill.",
          concept: { key: "stop", name: "Run bounds", axis: "problem" },
          teach: {
            title: "Done is a node",
            body: "Happy path ends. Error path catches. Infinite Wait-in-a-loop without a cap is an incident.",
          },
          questions: [
            identify(
              "Which graph never finishes?",
              "Wait 1s → HTTP → Wait 1s → (no IF, wire back to start) forever.",
              ["Uncapped loop", "A normal cron", "A form trigger", "A dead-letter"],
              0,
              "Cap or it burns.",
            ),
            scenario(
              "Staging burned 40,000 executions overnight.",
              "A Wait node loops to the trigger with no counter.",
              ["Hard cap + break condition", "Add more AI", "Delete logs", "Raise parallelism"],
              0,
              "Budgets.",
            ),
            order("After a failure.", ["Catch the error", "Write a dead-letter row", "Alert a human", "Do not retry forever"], "Visible failure."),
          ],
        },
        {
          key: "first-flow",
          title: "Mini-project: Form to inbox",
          summary: "On paper: trigger, map, send, test pin.",
          kind: "project",
          minutes: 12,
          concept: { key: "first-flow", name: "First graph", axis: "execution" },
          teach: {
            title: "You do not press Execute here",
            body: "Pick the nodes. Order them. Name the sample. That is the ship bar for this room.",
          },
          questions: [
            challenge(
              "Form to inbox",
              "Job: new lead email lands in sales@ . Simulated canvas only.",
              [
                { question: "Start?", options: ["A 200-node AI mesh", "Form / webhook trigger", "Cron scraping Gmail every second", "Manual copy forever"], answer: 1, explanation: "The form is the birth." },
                { question: "Before send?", options: ["Twelve agents", "Map name and email", "Tweet the payload", "Delete the form"], answer: 1, explanation: "Map." },
                { question: "Prove it?", options: ["Hope", "Pin one sample and walk the path", "Ship to prod first", "Hide errors"], answer: 1, explanation: "Rehearse." },
              ],
              "Trigger, map, send, pin.",
              "hard",
              100,
            ),
          ],
        },
      ],
    },
    {
      key: "apps",
      title: "Connect Apps",
      subtitle: "Form, email, database",
      missions: [
        {
          key: "creds",
          title: "Keys are not decorations",
          summary: "Least privilege. A store, not a screenshot.",
          concept: { key: "creds", name: "Credentials", axis: "knowledge" },
          teach: {
            title: "Connect once",
            body: "Slack, Gmail, Sheets live in a credential store. The canvas sees a name. Git sees nothing.",
          },
          example: {
            title: "Leak",
            body: "Exported workflow JSON with a Bearer token in a header field. That file will be copied. That token will be burned.",
            callout: "If it is in the export, it is already public-adjacent.",
          },
          questions: [
            identify(
              "Bad auth placement?",
              "https://api.example.com?token=SECRET",
              ["Token in query string", "Bearer header from a credential", "OAuth via the store", "No token because GET is public"],
              0,
              "Query strings leak in logs.",
            ),
            scenario(
              "An intern commits workflow JSON to GitHub.",
              "A Set node holds the live Stripe key.",
              ["Rotate the key and move it to credentials", "Add a README", "It's fine if the repo is “private-ish”", "Encode it in Base64"],
              0,
              "Rotate + vault.",
            ),
            order("Add Gmail.", ["Create a credential", "Least-privilege scopes", "Attach to the node by name", "Never paste the secret in a Set"], "Store, then attach."),
          ],
        },
        {
          key: "lead-shape",
          title: "Store, then ping",
          summary: "Don't lose the inbound.",
          concept: { key: "lead-shape", name: "App order", axis: "execution" },
          teach: {
            title: "Durability first",
            body: "Sheet or CRM write before Slack. If Slack 500s, you still have the row.",
          },
          example: {
            title: "Lost lead",
            body: "Slack first. Slack down. No row. The form thought it succeeded.",
            callout: "The system of record is not a chat channel.",
          },
          questions: [
            identify(
              "Best shape for lead + notify?",
              "A) Form → Slack only  B) Form → Sheet → Slack  C) Twelve AI agents  D) Manual copy",
              ["B — store then ping", "A — chat only", "C — agents", "D — intern"],
              0,
              "Row, then ping.",
            ),
            scenario(
              "Slack is red. The form still returns 200.",
              "You wrote the sheet first.",
              ["Sales can recover from the sheet", "The lead is gone forever", "Delete the sheet", "Add more agents"],
              0,
              "System of record.",
            ),
            order("Inbound.", ["Accept form", "Write system of record", "Notify Slack", "Alert if notify fails"], "Durable, then loud."),
          ],
        },
        {
          key: "scope",
          title: "The node should not be God",
          summary: "One app, one job.",
          concept: { key: "scope", name: "Least privilege", axis: "problem" },
          teach: {
            title: "Read vs write",
            body: "A notifier does not need drive-wide delete. A sheet append does not need admin on the whole domain.",
          },
          questions: [
            identify(
              "Over-scoped?",
              "Gmail credential: full mailbox read+send+delete, used only to send a thank-you.",
              ["Send-only would do", "Delete is required to send", "Always request all scopes", "Scopes are decorative"],
              0,
              "Least privilege.",
            ),
            scenario(
              "A compromised workflow can empty the company drive.",
              "The Sheets node only appends one tab.",
              ["Narrow the credential to that file / append", "Keep domain admin “in case”", "Put the key in the URL", "Disable logs"],
              0,
              "Shrink the blast.",
            ),
            identify(
              "Which is the system of record?",
              "Slack #sales vs CRM contact vs a screenshot in chat.",
              ["CRM / sheet row", "Slack", "Screenshot", "A vibe"],
              0,
              "Rows outlive pings.",
            ),
          ],
        },
        {
          key: "boss-leak",
          title: "Boss: The Leaking Canvas",
          summary: "Security review in twenty minutes. Simulated graph only.",
          kind: "boss",
          minutes: 14,
          concept: { key: "boss-leak", name: "Secret emergency", axis: "problem" },
          teach: {
            title: "Four faults",
            body: "Secret on canvas, token in query, Slack before row, god-credential. Find them. Do not add AI.",
          },
          questions: [
            challenge(
              "THE LEAKING CANVAS",
              "Exported JSON. Header token in a Set. Slack node first. Gmail credential is domain admin. Form trigger also cron-polls the same sheet.",
              [
                { question: "Secret?", options: ["Leave it", "Move to credential store and rotate", "Base64", "Tweet it"], answer: 1, explanation: "Vault + rotate." },
                { question: "Order?", options: ["Slack first is fine", "Write the row, then notify", "Delete the form", "More agents"], answer: 1, explanation: "Durable first." },
                { question: "Scope?", options: ["Keep admin", "Send/append only", "Add delete-all", "Hide the node"], answer: 1, explanation: "Least privilege." },
                { question: "Double birth?", options: ["Keep webhook and cron", "One trigger for one event", "Add a third trigger", "Interval 50ms"], answer: 1, explanation: "One birth." },
              ],
              "Vault, order, scope, one start.",
              "hard",
              250,
            ),
          ],
        },
      ],
    },
    {
      key: "data",
      title: "Data",
      subtitle: "JSON, fields, mapping, transforms",
      missions: [
        {
          key: "items",
          title: "Items are arrays of json",
          summary: "The path is exact. Case is a bug.",
          concept: { key: "items", name: "JSON paths", axis: "execution" },
          teach: {
            title: "Map with a finger on the sample",
            body: "n8n items look like { json: { ... } }. {{ $json.email }} is not {{ $json.Email }}. Guessing paths is how empty mails ship.",
          },
          questions: [
            identify(
              "Broken mapping?",
              "{{ $json.Email }} but payload has email",
              ["Wrong case / path", "Need more nodes", "JSON is illegal", "Triggers can't read fields"],
              0,
              "Paths are exact.",
            ),
            order("Map a field.", ["Pin a sample", "Read the real key", "Write the expression", "Send a test"], "See, then map."),
            scenario(
              "CRM gets blank phones. Payload shows \"phone\": \"+44 7700\".",
              "Expression used $json.mobile.",
              ["Fix the path, then transform", "Add an AI node to guess", "Delete CRM", "More Slack"],
              0,
              "Wrong key.",
            ),
          ],
        },
        {
          key: "transform",
          title: "Clean it before you send it",
          summary: "Garbage in, Slack out.",
          concept: { key: "transform", name: "Transforms", axis: "execution" },
          teach: {
            title: "At the edge",
            body: "Trim. Parse. Digits-only phone. Do it in Set/Function before the CRM node, not after the 404.",
          },
          questions: [
            identify(
              "Where do digits-only belong?",
              "Phone is “+44 7700”. CRM wants digits.",
              ["A Set/Function before the CRM node", "After the CRM 404s", "In Slack jokes", "Never"],
              0,
              "Transform at the edge.",
            ),
            scenario(
              "Names arrive as \" ada  smith \". CRM duplicates Ada / ada / ADA.",
              "No trim, no case policy.",
              ["Trim + a single case rule before upsert", "Store all variants forever", "AI rewrite of the whole company", "Delete CRM"],
              0,
              "Normalise once.",
            ),
            order("Phone clean.", ["Read raw string", "Strip to digits", "Validate length", "Map into CRM field"], "Clean, then write."),
          ],
        },
        {
          key: "types-json",
          title: "Strings that pretend to be numbers",
          summary: "JSON types lie if you stringify everything.",
          concept: { key: "types-json", name: "Types", axis: "knowledge" },
          teach: {
            title: "Score >= 80 needs a number",
            body: "If score is \"80\" with quotes, some IFs will fail closed. Parse before you branch.",
          },
          questions: [
            identify(
              "Why did IF skip every lead?",
              "score is the string \"90\". IF tests score >= 80 with numeric compare.",
              ["Type mismatch — parse first", "IF nodes are illegal", "Need more Slack", "Triggers can't branch"],
              0,
              "Parse.",
            ),
            scenario(
              "Amounts look like \"£1,200\". Finance SUM is zero.",
              "You mapped the pretty string into a number field.",
              ["Strip currency and commas, then number", "Add AI", "Send to Slack as-is forever", "Multiply by 0"],
              0,
              "Parse money.",
            ),
            identify(
              "Safest first look at a payload?",
              "A) Guess keys  B) Open the pinned sample  C) Ship to prod  D) Delete the node",
              ["B — the sample", "A — guess", "C — prod", "D — delete"],
              0,
              "Look.",
            ),
          ],
        },
      ],
    },
    {
      key: "logic",
      title: "Logic",
      subtitle: "IF, filters, branches",
      missions: [
        {
          key: "if",
          title: "Only alert when it matters",
          summary: "Don't page sales for spam.",
          concept: { key: "if", name: "Branching", axis: "execution" },
          teach: {
            title: "IF is a bouncer",
            body: "Work email + size threshold → Slack. Else → cold sheet. Branches can stop. They do not all reconvene.",
          },
          questions: [
            scenario(
              "Every form pings #sales including “asdf”.",
              "You have company size and email.",
              ["Add an IF: work email + size threshold", "Mute Slack globally", "Hire an intern to click", "Delete IF nodes — they slow things"],
              0,
              "Filter early.",
            ),
            identify(
              "Must both branches join?",
              "True → Slack. False → sheet. No merge node.",
              ["Fine — branches can stop", "Illegal in n8n", "Will crash the server", "Must tweet both"],
              0,
              "They can stop.",
            ),
            order("Filter spam.", ["Read email domain", "IF work domain", "True: notify", "False: cold store"], "Bouncer first."),
          ],
        },
        {
          key: "switch",
          title: "More than two doors",
          summary: "Switch on intent, not a spaghetti of IFs.",
          concept: { key: "switch", name: "Switch", axis: "execution" },
          teach: {
            title: "Named exits",
            body: "Support vs sales vs legal. One Switch. Default path for unknown. Nested IF pyramids are how incidents hide.",
          },
          questions: [
            identify(
              "Cleanest for three intents?",
              "sales | support | legal | other",
              ["One Switch + default", "Twelve nested IFs", "One HTTP to nowhere", "No branch — always refund"],
              0,
              "Switch.",
            ),
            scenario(
              "Unknown intent currently refunds automatically.",
              "Default wire goes to Stripe.",
              ["Default to a human queue", "Keep auto-refund", "Delete Switch", "Page the CEO on every form"],
              0,
              "Fail closed.",
            ),
            order("Route a ticket.", ["Classify intent", "Switch", "Specialised path", "Default to human"], "Known doors, then a catch."),
          ],
        },
        {
          key: "filter-early",
          title: "Cheap checks first",
          summary: "Don't call GPT to see if the email is empty.",
          concept: { key: "filter-early", name: "Cheap filters", axis: "problem" },
          teach: {
            title: "Bouncer before the band",
            body: "Empty payload, duplicate ID, blocked domain — IF before HTTP, before AI, before Slack storms.",
          },
          questions: [
            identify(
              "First node after trigger?",
              "Payload may be empty. AI classify costs money. Slack is loud.",
              ["Empty / required-field IF", "AI first always", "Slack first always", "HTTP spray"],
              0,
              "Cheap first.",
            ),
            scenario(
              "AI bill 10× last week. Most items were empty forms.",
              "Classify node sits on the raw trigger.",
              ["Filter empties before the model", "Buy a bigger model", "Disable IF forever", "Parallel 100 AI nodes"],
              0,
              "Don't pay for garbage.",
            ),
            identify(
              "Duplicate inbound ID seen twice in 2 seconds.",
              "No idempotency key.",
              ["Dedupe on ID before writes", "Write twice — it's fine", "Delete the trigger", "Add more Slack"],
              0,
              "Idempotent.",
            ),
          ],
        },
      ],
    },
    {
      key: "http",
      title: "APIs",
      subtitle: "HTTP, auth, endpoints — on paper",
      missions: [
        {
          key: "verbs",
          title: "Talk to the outside world",
          summary: "The HTTP Request node is a letter, not a personality.",
          concept: { key: "verbs", name: "HTTP verbs", axis: "execution" },
          teach: {
            title: "Method, URL, headers, body",
            body: "GET to read. POST to create. Bearer in headers from a credential, not the URL. You will not fire this request in the game.",
          },
          questions: [
            identify(
              "GET is for…",
              "A) Read  B) Create  C) 401  D) 429",
              ["Read", "Create", "Auth failed", "Rate limited"],
              0,
              "GET reads.",
            ),
            identify(
              "401 means…",
              "A) Read  B) Create  C) Auth failed  D) Rate limited",
              ["Auth failed", "Read", "Create", "Success"],
              0,
              "Check the credential.",
            ),
            order("Call an API.", ["Pick method", "Set URL", "Attach auth from store", "Map body from $json", "Handle status"], "Letter, then stamp."),
            scenario(
              "POST works in Postman. n8n graph 401s.",
              "Token was pasted in the URL in Postman. Canvas uses an empty header.",
              ["Put Bearer in the credential / header", "Add AI", "Switch to GET for creates", "Disable HTTPS"],
              0,
              "Auth belongs in the store.",
            ),
          ],
        },
        {
          key: "status",
          title: "Status is a clue",
          summary: "429 is a wait. 500 is a retry budget. 404 is a path lie.",
          concept: { key: "status", name: "HTTP status", axis: "problem" },
          teach: {
            title: "Don't retry 401 forever",
            body: "401 needs a human and a rotated secret. 429 needs backoff. Treating every error as “try harder” is how you DDoS a partner.",
          },
          questions: [
            identify(
              "429 means…",
              "Partner API returns 429 with Retry-After: 30.",
              ["Rate limited — wait / batch", "Success", "Delete the workflow", "Auth is perfect"],
              0,
              "Breathe.",
            ),
            scenario(
              "You fire 100 parallel HTTP nodes for “speed.”",
              "Partner SLA is 5 rps.",
              ["SplitInBatches + wait", "More parallelism", "Ignore 429", "Put tokens in query"],
              0,
              "Batch and breathe.",
            ),
            identify(
              "Infinite retry on 401?",
              "Credential expired.",
              ["Stop and alert — rotate", "Retry until the heat death", "It's a 429", "Switch method to GET"],
              0,
              "401 is not patience.",
            ),
          ],
        },
        {
          key: "body",
          title: "The body is a contract",
          summary: "JSON in, JSON out — don't smuggle HTML.",
          concept: { key: "body", name: "Request body", axis: "execution" },
          teach: {
            title: "Content-Type is a promise",
            body: "If they want application/json, a form-encoded blob is a 400. Map fields. Don't paste a novel.",
          },
          questions: [
            identify(
              "Likely 400?",
              "Content-Type: application/json. Body: name=Ada&email=ada@test",
              ["Wrong body shape vs header", "Need more Slack", "GET required", "n8n forbids POST"],
              0,
              "Shape vs header.",
            ),
            order("POST a contact.", ["Read API field names", "Map from $json", "Set JSON body", "Check 2xx", "Store returned id"], "Contract, then id."),
            scenario(
              "Create returns 201 but you never save the id.",
              "Later upserts duplicate the human.",
              ["Write the external id back to your sheet/CRM", "Ignore ids", "Delete 201s", "Add a second create"],
              0,
              "Keep the handle.",
            ),
          ],
        },
      ],
    },
    {
      key: "loop",
      title: "Loops",
      subtitle: "100 records, one brain",
      missions: [
        {
          key: "batch",
          title: "Process the list",
          summary: "Split in batches. Don't melt the API.",
          concept: { key: "batch", name: "Batching", axis: "execution" },
          teach: {
            title: "Item lists",
            body: "One item per record. SplitInBatches with waits. Honour 429. This is a diagram, not a live split.",
          },
          questions: [
            identify(
              "100 CRM updates. Best?",
              "A) One giant dump, no delay  B) SplitInBatches + wait  C) 100 workflows by hand  D) Ignore errors",
              ["SplitInBatches + wait", "Giant dump", "100 workflows", "Ignore errors"],
              0,
              "Batch and breathe.",
            ),
            scenario(
              "Always fire 100 parallel HTTP nodes for speed.",
              "You 429 and miss writes.",
              ["False — you'll 429 and miss writes", "True — parallelism is free", "True — n8n caps magic", "True — partners love it"],
              0,
              "Don't.",
            ),
            order("A list.", ["Load items", "SplitInBatches", "HTTP per batch", "Wait / honour 429", "Continue"], "Chunk the storm."),
          ],
        },
        {
          key: "errors-loop",
          title: "One bad row must not kill 99",
          summary: "Continue on fail, then a report.",
          concept: { key: "errors-loop", name: "Partial failure", axis: "problem" },
          teach: {
            title: "Isolate",
            body: "A 400 on row 17 should dead-letter 17, not abort the payroll file. You design the setting. You do not flip it in a real runtime here.",
          },
          questions: [
            identify(
              "Row 17 of 100 400s. Desired?",
              "Payroll file.",
              ["Dead-letter 17, finish the rest", "Abort all", "Retry 17 a million times with no cap", "Delete the file"],
              0,
              "Isolate.",
            ),
            scenario(
              "Continue-on-fail is off. First 401 stops a 10,000-row sync.",
              "Overnight window missed.",
              ["Isolate errors + alert + resume", "Keep fail-fast on bulk syncs always", "Hide the 401", "Add AI classify on each row first"],
              0,
              "Bulk wants isolation.",
            ),
            order("After a bad item.", ["Catch", "Write dead-letter", "Continue batch", "Summary alert"], "Leave a trail."),
          ],
        },
        {
          key: "idempotent",
          title: "Don't create Ada twice",
          summary: "Upsert on email. Replay-safe.",
          concept: { key: "idempotent", name: "Idempotency", axis: "execution" },
          teach: {
            title: "The same event twice",
            body: "Webhooks retry. If create-on-email with no lookup, Ada is twins. Key on email. Upsert.",
          },
          questions: [
            identify(
              "Identity for a person?",
              "A) Name only  B) Email as unique key  C) Company tweet  D) IP",
              ["Email as unique key", "Name only", "Tweet", "IP"],
              0,
              "Upsert key.",
            ),
            scenario(
              "Replay of the same form id creates a second CRM contact.",
              "No lookup.",
              ["Upsert keyed on email / external id", "Create always", "Delete CRM", "Slack the duplicates into a thread"],
              0,
              "Replay-safe.",
            ),
            identify(
              "Safe replay?",
              "Same webhook body twice.",
              ["Second run updates the same row", "Second run always inserts", "Second run refunds", "Second run pages the CEO"],
              0,
              "Same row.",
            ),
          ],
        },
      ],
    },
    {
      key: "ai",
      title: "AI in the flow",
      subtitle: "Classify, then file — still a sim",
      missions: [
        {
          key: "json-out",
          title: "The model is a node, not the boss",
          summary: "Ask for JSON. Validate. Then write.",
          concept: { key: "json-out", name: "Structured AI", axis: "execution" },
          teach: {
            title: "Never skip validate",
            body: "If the model says “urgent”, you still apply rules. You will not call a live model in this world.",
          },
          questions: [
            order("AI classify.", ["Receive form", "Prompt for a JSON label", "Validate the label", "Write DB", "Email the team"], "Never skip validate."),
            identify(
              "Skip IF because the model said urgent?",
              "Label: urgent. Policy: only page if amount > 500.",
              ["Still apply rules", "Page everyone", "Delete IF nodes", "Tweet legal"],
              0,
              "Policy wins.",
            ),
            scenario(
              "Model returns a poem instead of {\"intent\":\"sales\"}.",
              "Next node expected JSON.",
              ["Fail closed, dead-letter, human", "Write the poem to CRM", "Retry infinite", "Trust the vibe"],
              0,
              "Validate.",
            ),
          ],
        },
        {
          key: "cost-ai",
          title: "Pay for thinking, not for empties",
          summary: "Filter, then model.",
          concept: { key: "cost-ai", name: "AI cost", axis: "problem" },
          teach: {
            title: "Tokens are rent",
            body: "A classify node on raw spam is a donation to the GPU landlord.",
          },
          questions: [
            identify(
              "Cheapest correct order?",
              "Spam, empties, then intent.",
              ["Filter → maybe AI → write", "AI → everything", "Slack → AI → hope", "100 parallel models"],
              0,
              "Filter first.",
            ),
            scenario(
              "You send the entire PDF wiki in every prompt “for RAG.”",
              "Each run costs a small car.",
              ["Retrieve a few chunks, then generate", "Paste the wiki forever", "Disable filters", "Bigger context always"],
              0,
              "Retrieve, don't paste.",
            ),
            order("Intent.", ["Cheap filters", "Model JSON", "Schema check", "Route Switch"], "Pay once, on clean input."),
          ],
        },
        {
          key: "biz",
          title: "Mini-project: The revenue pipe",
          summary: "Lead → enrich → score → CRM → Slack → follow-up. Diagram only.",
          kind: "project",
          minutes: 14,
          concept: { key: "biz", name: "Revenue automation", axis: "problem" },
          teach: {
            title: "Idempotent writes",
            body: "Don't create duplicate CRM contacts. Key on email. Time is a node.",
          },
          questions: [
            challenge(
              "The pipe",
              "Inbound lead must be enriched, scored, upserted, notified, followed up in 24h. Simulated.",
              [
                { question: "Identity?", options: ["Name only", "Email as unique key", "Company tweet", "IP"], answer: 1, explanation: "Upsert key." },
                { question: "Score 90+?", options: ["Slack + assign owner", "Delete", "Ignore", "Tweet"], answer: 0, explanation: "Wake a human." },
                { question: "Follow-up?", options: ["Hope", "Scheduled wait + email if still open", "Spam hourly", "CC the company"], answer: 1, explanation: "Time is a node." },
                { question: "Failures?", options: ["Silent", "Catch + dead-letter + alert", "Retry infinite", "Delete the run"], answer: 1, explanation: "Visible failure." },
              ],
              "Idempotent and paced.",
              "hard",
              100,
            ),
          ],
        },
      ],
    },
    {
      key: "final",
      title: "Final Boss: Automate the Company",
      subtitle: "A fictional firm. You design the architecture. Nothing executes.",
      isBoss: true,
      missions: [
        {
          key: "final",
          title: "AUTOMATE THE COMPANY",
          summary: "The whole map. Four domains. Shared secrets. Error paths.",
          kind: "boss",
          minutes: 16,
          concept: { key: "final", name: "Automation architecture", axis: "problem" },
          teach: {
            title: "Systems, not spaghetti",
            body: "Inbound, ops, support, reporting — four flows, shared credentials, error paths. You ship a blueprint.",
          },
          questions: [
            challenge(
              "AUTOMATE THE COMPANY",
              "Studio of 12. Leads, invoices, support mails, a weekly KPI ping. Simulated architecture only.",
              [
                { question: "How many workflows?", options: ["One 200-node monster", "Separate flows per domain + shared error handler", "No workflows — vibes", "One per email"], answer: 1, explanation: "Split by domain." },
                { question: "Failures?", options: ["Silent", "Catch + dead-letter + alert", "Retry infinite", "Delete the run"], answer: 1, explanation: "Visible failure." },
                { question: "Secrets?", options: ["In every JSON export", "Credential store, least privilege, rotate on leak", "Query-string tokens", "Slack the keys"], answer: 1, explanation: "Vault." },
                { question: "Weekly KPI?", options: ["Someone remembers", "Cron trigger → warehouse query → Slack", "Print screenshots", "Pause n8n"], answer: 1, explanation: "Cron is a trigger." },
              ],
              "Architecture is the skill.",
              "hard",
              1000,
            ),
          ],
        },
      ],
    },
  ],
});
