/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppAchievementsRouteImport } from './routes/_app/achievements'
import { Route as AppChallengesRouteImport } from './routes/_app/challenges'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppPricingRouteImport } from './routes/_app/pricing'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as ApiAuthDebugRouteImport } from './routes/api/auth-debug'
import { Route as TrySlugRouteImport } from './routes/try.$slug'
import { Route as AppLearnLessonIdRouteImport } from './routes/_app/learn.$lessonId'
import { Route as AppPracticeConceptIdRouteImport } from './routes/_app/practice.$conceptId'
import { Route as AppSkillsIndexRouteImport } from './routes/_app/skills.index'
import { Route as AppSkillsSlugRouteImport } from './routes/_app/skills.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as AppSkillsSlugTreeRouteImport } from './routes/_app/skills.$slug.tree'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesRoute = AppChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthDebugRoute = ApiAuthDebugRouteImport.update({
  id: '/api/auth-debug',
  path: '/api/auth-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrySlugRoute = TrySlugRouteImport.update({
  id: '/try/$slug',
  path: '/try/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLearnLessonIdRoute = AppLearnLessonIdRouteImport.update({
  id: '/learn/$lessonId',
  path: '/learn/$lessonId',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeConceptIdRoute = AppPracticeConceptIdRouteImport.update({
  id: '/practice/$conceptId',
  path: '/practice/$conceptId',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsIndexRoute = AppSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsSlugRoute = AppSkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSkillsSlugTreeRoute = AppSkillsSlugTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => AppSkillsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AppAchievementsRoute
  '/challenges': typeof AppChallengesRoute
  '/explore': typeof AppExploreRoute
  '/home': typeof AppHomeRoute
  '/pricing': typeof AppPricingRoute
  '/profile': typeof AppProfileRoute
  '/api/auth-debug': typeof ApiAuthDebugRoute
  '/try/$slug': typeof TrySlugRoute
  '/learn/$lessonId': typeof AppLearnLessonIdRoute
  '/practice/$conceptId': typeof AppPracticeConceptIdRoute
  '/skills/$slug': typeof AppSkillsSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/skills/': typeof AppSkillsIndexRoute
  '/skills/$slug/tree': typeof AppSkillsSlugTreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AppAchievementsRoute
  '/challenges': typeof AppChallengesRoute
  '/explore': typeof AppExploreRoute
  '/home': typeof AppHomeRoute
  '/pricing': typeof AppPricingRoute
  '/profile': typeof AppProfileRoute
  '/api/auth-debug': typeof ApiAuthDebugRoute
  '/try/$slug': typeof TrySlugRoute
  '/learn/$lessonId': typeof AppLearnLessonIdRoute
  '/practice/$conceptId': typeof AppPracticeConceptIdRoute
  '/skills/$slug': typeof AppSkillsSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/skills': typeof AppSkillsIndexRoute
  '/skills/$slug/tree': typeof AppSkillsSlugTreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/documentation': typeof DocumentationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/challenges': typeof AppChallengesRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/profile': typeof AppProfileRoute
  '/api/auth-debug': typeof ApiAuthDebugRoute
  '/try/$slug': typeof TrySlugRoute
  '/_app/learn/$lessonId': typeof AppLearnLessonIdRoute
  '/_app/practice/$conceptId': typeof AppPracticeConceptIdRoute
  '/_app/skills/$slug': typeof AppSkillsSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_app/skills/': typeof AppSkillsIndexRoute
  '/_app/skills/$slug/tree': typeof AppSkillsSlugTreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/achievements'
    | '/challenges'
    | '/explore'
    | '/home'
    | '/pricing'
    | '/profile'
    | '/api/auth-debug'
    | '/try/$slug'
    | '/learn/$lessonId'
    | '/practice/$conceptId'
    | '/skills/$slug'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/skills/'
    | '/skills/$slug/tree'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/achievements'
    | '/challenges'
    | '/explore'
    | '/home'
    | '/pricing'
    | '/profile'
    | '/api/auth-debug'
    | '/try/$slug'
    | '/learn/$lessonId'
    | '/practice/$conceptId'
    | '/skills/$slug'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/skills'
    | '/skills/$slug/tree'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/documentation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/achievements'
    | '/_app/challenges'
    | '/_app/explore'
    | '/_app/home'
    | '/_app/pricing'
    | '/_app/profile'
    | '/api/auth-debug'
    | '/try/$slug'
    | '/_app/learn/$lessonId'
    | '/_app/practice/$conceptId'
    | '/_app/skills/$slug'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/_app/skills/'
    | '/_app/skills/$slug/tree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DocumentationRoute: typeof DocumentationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAuthDebugRoute: typeof ApiAuthDebugRoute
  TrySlugRoute: typeof TrySlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenges': {
      id: '/_app/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AppChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth-debug': {
      id: '/api/auth-debug'
      path: '/api/auth-debug'
      fullPath: '/api/auth-debug'
      preLoaderRoute: typeof ApiAuthDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try/$slug': {
      id: '/try/$slug'
      path: '/try/$slug'
      fullPath: '/try/$slug'
      preLoaderRoute: typeof TrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/learn/$lessonId': {
      id: '/_app/learn/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof AppLearnLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/$conceptId': {
      id: '/_app/practice/$conceptId'
      path: '/practice/$conceptId'
      fullPath: '/practice/$conceptId'
      preLoaderRoute: typeof AppPracticeConceptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills/': {
      id: '/_app/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof AppSkillsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills/$slug': {
      id: '/_app/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof AppSkillsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/skills/$slug/tree': {
      id: '/_app/skills/$slug/tree'
      path: '/tree'
      fullPath: '/skills/$slug/tree'
      preLoaderRoute: typeof AppSkillsSlugTreeRouteImport
      parentRoute: typeof AppSkillsSlugRoute
    }
  }
}

interface AppSkillsSlugRouteChildren {
  AppSkillsSlugTreeRoute: typeof AppSkillsSlugTreeRoute
}

const AppSkillsSlugRouteChildren: AppSkillsSlugRouteChildren = {
  AppSkillsSlugTreeRoute: AppSkillsSlugTreeRoute,
}

const AppSkillsSlugRouteWithChildren = AppSkillsSlugRoute._addFileChildren(
  AppSkillsSlugRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppChallengesRoute: typeof AppChallengesRoute
  AppExploreRoute: typeof AppExploreRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPricingRoute: typeof AppPricingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppLearnLessonIdRoute: typeof AppLearnLessonIdRoute
  AppPracticeConceptIdRoute: typeof AppPracticeConceptIdRoute
  AppSkillsSlugRoute: typeof AppSkillsSlugRouteWithChildren
  AppSkillsIndexRoute: typeof AppSkillsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppChallengesRoute: AppChallengesRoute,
  AppExploreRoute: AppExploreRoute,
  AppHomeRoute: AppHomeRoute,
  AppPricingRoute: AppPricingRoute,
  AppProfileRoute: AppProfileRoute,
  AppLearnLessonIdRoute: AppLearnLessonIdRoute,
  AppPracticeConceptIdRoute: AppPracticeConceptIdRoute,
  AppSkillsSlugRoute: AppSkillsSlugRouteWithChildren,
  AppSkillsIndexRoute: AppSkillsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DocumentationRoute: DocumentationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAuthDebugRoute: ApiAuthDebugRoute,
  TrySlugRoute: TrySlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
